
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chalu
 */
public class Interface_questions extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface_questions.class.getName());

    /**
     * Creates new form Interface_questions
     */
    public Interface_questions() {
        initComponents();
        initialiserQuestions();
        afficher_question_courante();
    }
    private Random random = new Random();
private int score = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_question = new javax.swing.JLabel();
        bouton_1 = new javax.swing.JButton();
        bouton_2 = new javax.swing.JButton();
        bouton_3 = new javax.swing.JButton();
        bouton_4 = new javax.swing.JButton();
        label_juste = new javax.swing.JLabel();
        bouton_qsuiv = new javax.swing.JButton();
        label_score = new javax.swing.JLabel();
        start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_question.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_question.setForeground(new java.awt.Color(0, 0, 102));
        label_question.setText("Bonjour");

        bouton_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bouton_1.setForeground(new java.awt.Color(0, 0, 255));
        bouton_1.setText("jButton1");
        bouton_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouton_1MouseClicked(evt);
            }
        });
        bouton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_1ActionPerformed(evt);
            }
        });

        bouton_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bouton_2.setForeground(new java.awt.Color(0, 51, 255));
        bouton_2.setText("jButton2");
        bouton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_2ActionPerformed(evt);
            }
        });

        bouton_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bouton_3.setForeground(new java.awt.Color(0, 0, 255));
        bouton_3.setText("jButton3");
        bouton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_3ActionPerformed(evt);
            }
        });

        bouton_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bouton_4.setForeground(new java.awt.Color(0, 51, 255));
        bouton_4.setText("jButton4");
        bouton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_4ActionPerformed(evt);
            }
        });

        label_juste.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_juste.setForeground(new java.awt.Color(255, 0, 0));
        label_juste.setText("jLabel2");

        bouton_qsuiv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bouton_qsuiv.setForeground(new java.awt.Color(255, 0, 0));
        bouton_qsuiv.setText("Question suivante");
        bouton_qsuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_qsuivActionPerformed(evt);
            }
        });

        label_score.setText("score : x/n");

        start.setText("jButton1");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bouton_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(319, 319, 319)
                        .addComponent(bouton_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(label_question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bouton_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_juste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(319, 319, 319)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bouton_qsuiv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bouton_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(start)
                .addGap(289, 289, 289)
                .addComponent(label_score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_score, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_question, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton_2)
                    .addComponent(bouton_1))
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton_4)
                    .addComponent(bouton_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_juste)
                    .addComponent(bouton_qsuiv))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_3ActionPerformed
        verifierReponse(3);
    }//GEN-LAST:event_bouton_3ActionPerformed

    private void bouton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_1ActionPerformed
        verifierReponse(1);
    }//GEN-LAST:event_bouton_1ActionPerformed

    private void bouton_qsuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_qsuivActionPerformed
   // Tirer un index aléatoire entre 0 et questions.length - 1
    indexQuestionCourante = random.nextInt(questions.length);

    // Réactiver les boutons
    bouton_1.setEnabled(true);
    bouton_2.setEnabled(true);
    bouton_3.setEnabled(true);
    bouton_4.setEnabled(true);

    // Effacer le message
    label_juste.setText("");

    // Afficher la nouvelle question
    afficher_question_courante();

    }//GEN-LAST:event_bouton_qsuivActionPerformed

    private void bouton_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton_1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bouton_1MouseClicked

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_startMouseClicked

    private void bouton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_2ActionPerformed
        verifierReponse(2);
    }//GEN-LAST:event_bouton_2ActionPerformed

    private void bouton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_4ActionPerformed
        verifierReponse(4);
    }//GEN-LAST:event_bouton_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface_questions().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_1;
    private javax.swing.JButton bouton_2;
    private javax.swing.JButton bouton_3;
    private javax.swing.JButton bouton_4;
    private javax.swing.JButton bouton_qsuiv;
    private javax.swing.JLabel label_juste;
    private javax.swing.JLabel label_question;
    private javax.swing.JLabel label_score;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables

private Question[] questions;
private int indexQuestionCourante = 0;

private void initialiserQuestions() {

    questions = new Question[] {
    new Question("Quelle est la capitale de l’Italie ?", "Rome", "Milan", "Venise", "Naples", 1),
    new Question("Quel est le plus grand océan ?", "Atlantique", "Pacifique", "Indien", "Arctique", 2),
    new Question("Combien de côtés possède un hexagone ?", "5", "6", "7", "8", 2),
    new Question("Qui a peint la Joconde ?", "Van Gogh", "Léonard de Vinci", "Picasso", "Monet", 2),
    new Question("Quelle est la planète la plus proche du Soleil ?", "Terre", "Vénus", "Mercure", "Mars", 3),
    new Question("En quelle année l’euro a-t-il été mis en circulation ?", "1999", "2002", "1995", "2005", 2),
    new Question("Quelle est la langue la plus parlée au monde ?", "Anglais", "Espagnol", "Mandarin", "Arabe", 3),
    new Question("Quelle est la formule chimique de l’eau ?", "CO₂", "H₂O", "O₂", "H₂", 2),
    new Question("Quel est le plus long fleuve du monde ?", "Amazone", "Nil", "Yangtsé", "Mississippi", 1),
    new Question("Combien y a-t-il de bits dans un octet ?", "4", "8", "16", "32", 2),
    new Question("Dans quel pays se trouve la Tour de Pise ?", "France", "Italie", "Espagne", "Portugal", 2),
    new Question("Quel est le plus grand désert du monde ?", "Sahara", "Gobi", "Antarctique", "Kalahari", 3),
new Question("Quel est le symbole chimique de l’or ?", "Ag", "Fe", "Au", "O", 3),
new Question("Combien de continents compte-t-on généralement ?", "4", "5", "6", "7", 4),
new Question("Quel est l’organe principal de la respiration chez l’être humain ?", "Cœur", "Poumons", "Foie", "Reins", 2),
new Question("Qui a écrit Le Petit Prince ?", "Victor Hugo", "Albert Camus", "Antoine de Saint-Exupéry", "Molière", 3),
new Question("Quelle est la planète la plus grande du système solaire ?", "Jupiter", "Saturne", "Uranus", "Neptune", 1),
new Question("Quel est l’animal terrestre le plus rapide ?", "Guépard", "Lion", "Tigre", "Antilope", 1),
new Question("Dans quel océan se trouve Madagascar ?", "Atlantique", "Indien", "Pacifique", "Arctique", 2),
new Question("Combien de minutes y a-t-il dans une heure ?", "30", "60", "90", "120", 2),
new Question("Quelle est la langue officielle du Brésil ?", "Espagnol", "Portugais", "Français", "Anglais", 2),
new Question("Quel est le plus grand mammifère marin ?", "Orque", "Requin baleine", "Baleine bleue", "Dauphin", 3),
new Question("De quel pays vient le sushi ?", "Chine", "Corée du Sud", "Vietnam", "Japon", 4),
new Question("Quelle est la capitale du Canada ?", "Toronto", "Ottawa", "Montréal", "Vancouver", 2),
new Question("Combien de degrés compte un angle droit ?", "45°", "90°", "120°", "180°", 2),
new Question("Quel est l’organe qui pompe le sang dans le corps ?", "Poumon", "Cœur", "Foie", "Estomac", 2),
new Question("Qui a découvert l’Amérique en 1492 ?", "Vasco de Gama", "Christophe Colomb", "Magellan", "James Cook", 2),
new Question("Dans quel pays se trouve la pyramide de Khéops ?", "Grèce", "Mexique", "Égypte", "Turquie", 3),
new Question("Quel est le point d’ébullition de l’eau au niveau de la mer ?", "0°C", "50°C", "100°C", "150°C", 3),
new Question("Quelle est la capitale de l’Australie ?", "Sydney", "Canberra", "Melbourne", "Perth", 2),
new Question("Quel est le plus long os du corps humain ?", "Radius", "Humérus", "Fémur", "Tibia", 3),
new Question("Quel mathématicien a donné son nom au théorème sur les triangles rectangles ?", "Newton", "Pythagore", "Euclide", "Thalès", 2),
new Question("Quelle est la monnaie utilisée au Japon ?", "Yuan", "Won", "Yen", "Dollar", 3),
new Question("Quel gaz les plantes absorbent-elles pour la photosynthèse ?", "Oxygène", "Hydrogène", "Azote", "Dioxyde de carbone", 4),
new Question("Quel est le plus grand pays du monde par sa superficie ?", "États-Unis", "Chine", "Russie", "Canada", 3),
new Question("De combien de couleurs est composé l’arc-en-ciel traditionnel ?", "5", "6", "7", "8", 3),
new Question("Qui a peint La Nuit étoilée ?", "Van Gogh", "Picasso", "Monet", "Dali", 1),
new Question("Quelle est la langue officielle de l’Allemagne ?", "Allemand", "Néerlandais", "Danois", "Anglais", 1),
new Question("Quel est le plus grand océan de la Terre ?", "Atlantique", "Indien", "Pacifique", "Arctique", 3),new Question("Combien de jours compte une année bissextile ?", "364", "365", "366", "367", 3),
new Question("Dans quel pays se situe Rio de Janeiro ?", "Argentine", "Mexique", "Brésil", "Chili", 3),
new Question("Qui a écrit Les Misérables ?", "Zola", "Balzac", "Victor Hugo", "Flaubert", 3),
new Question("Quelle est la capitale de l’Espagne ?", "Madrid", "Barcelone", "Valence", "Séville", 1),
new Question("Quel est l’animal emblème de l’Australie ?", "Koala", "Kangourou", "Émeu", "Diable de Tasmanie", 2),
new Question("Quelle unité mesure l’intensité du courant électrique ?", "Volt", "Ohm", "Watt", "Ampère", 4),
new Question("De quel pays provient la pizza ?", "Grèce", "Italie", "France", "États-Unis", 2),
new Question("Quel est l’océan à l’ouest de l’Europe ?", "Atlantique", "Pacifique", "Indien", "Arctique", 1),
new Question("Qui a développé la théorie de la relativité ?", "Einstein", "Galilée", "Newton", "Bohr", 1),
new Question("Dans quel pays se trouve le Taj Mahal ?", "Inde", "Pakistan", "Bangladesh", "Sri Lanka", 1),
new Question("Combien de joueurs y a-t-il dans une équipe de football sur le terrain ?", "9", "10", "11", "12", 3),
new Question("Quelle est la capitale de la Suisse ?", "Zurich", "Genève", "Berne", "Lausanne", 3),
new Question("Quel est le métal principal des pièces de 1 et 2 centimes d’euro ?", "Cuivre", "Or", "Fer", "Aluminium", 1),
new Question("Quel est le plus petit nombre premier ?", "0", "1", "2", "3", 3),
new Question("Quel est l’instrument de musique à touches et à cordes frappées ?", "Guitare", "Piano", "Violoncelle", "Flûte", 2),
new Question("Dans quel pays se trouve la ville de Marrakech ?", "Égypte", "Algérie", "Tunisie", "Maroc", 4),
new Question("Quel est le fleuve qui traverse Paris ?", "Rhin", "Seine", "Loire", "Garonne", 2),
new Question("Quel est le plus haut sommet du monde ?", "Mont Blanc", "K2", "Kilimandjaro", "Everest", 4),
new Question("Quelle est la capitale de la Grèce ?", "Athènes", "Rome", "Sofia", "Belgrade", 1),
new Question("Quel scientifique est associé à la loi de la gravitation universelle ?", "Einstein", "Newton", "Kepler", "Copernic", 2),
new Question("Quel est l’instrument de mesure de la température ?", "Altimètre", "Baromètre", "Thermomètre", "Hygromètre", 3),
    };
            }

    
    private void afficher_question_courante() {

    Question q = questions[indexQuestionCourante];   
    label_question.setText(q.intitule);
    bouton_1.setText(q.proposition1);
    bouton_2.setText(q.proposition2);
    bouton_3.setText(q.proposition3);
    bouton_4.setText(q.proposition4);

    bouton_1.setVisible(true);
    bouton_2.setVisible(true);
    bouton_3.setVisible(true);
    bouton_4.setVisible(true);
    //label_juste.setEnabled("cache");
    //label_score.setText("Score : " + score);
    label_score.setText("Score : " + score + " / " + questions.length);

}
    private void verifierReponse(int choix) {

    Question q = questions[indexQuestionCourante];

    if (choix == q.getIndexBonneReponse()) {
        label_juste.setText("Bonne réponse !");
        score++;    // AJOUT DU SCORE
    } else {
        label_juste.setText("Mauvaise réponse !");
    }

    // Mettre à jour le score affiché
    label_score.setText("Score : " + score + " / " + questions.length);

    // Désactiver les boutons
    bouton_1.setEnabled(false);
    bouton_2.setEnabled(false);
    bouton_3.setEnabled(false);
    bouton_4.setEnabled(false);

}}

