/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
/**
 *
 * @author chalu
 */
public class Interf_graphique extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interf_graphique.class.getName());

    
    
private cerveau_jeu cerveau = new cerveau_jeu();

    /**
     * Creates new form Interf_graphique
     */
    public Interf_graphique() {
        initComponents();
        jLabel3.setText("");
    cerveau.nouvellePartie();
        for (int i = 0; i < 4; i++) {
        joueur[i] = 0;          // Valeurs de départ pour le joueur
    }
       essaisRestants = 10;
label_nb_tentatives.setText("0 sur 10");
        majLabels();     
}

    public int compteur=0;
private int essaisRestants = 10; // nombre d'essais restants

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_plus = new javax.swing.JPanel();
        btp1 = new javax.swing.JButton();
        btp2 = new javax.swing.JButton();
        btp3 = new javax.swing.JButton();
        btp4 = new javax.swing.JButton();
        nombres = new javax.swing.JPanel();
        nb1 = new javax.swing.JLabel();
        nb2 = new javax.swing.JLabel();
        nb3 = new javax.swing.JLabel();
        nb4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btm1 = new javax.swing.JButton();
        btm2 = new javax.swing.JButton();
        btm3 = new javax.swing.JButton();
        btm4 = new javax.swing.JButton();
        label_juste = new javax.swing.JLabel();
        label_trh = new javax.swing.JLabel();
        label_trb = new javax.swing.JLabel();
        btn_check = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        label_nb_tentatives = new javax.swing.JLabel();
        btn_recom = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Trouve le bon code en 5 tentatives !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 310, 40));

        btn_plus.setLayout(new java.awt.GridLayout(1, 4));

        btp1.setText("/\\");
            btp1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btp1MouseClicked(evt);
                }
            });
            btp1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btp1ActionPerformed(evt);
                }
            });
            btn_plus.add(btp1);

            btp2.setText("/\\");
                btp2.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        btp2MouseClicked(evt);
                    }
                });
                btn_plus.add(btp2);

                btp3.setText("/\\");
                    btp3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            btp3MouseClicked(evt);
                        }
                    });
                    btn_plus.add(btp3);

                    btp4.setText("/\\");
                        btp4.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btp4MouseClicked(evt);
                            }
                        });
                        btn_plus.add(btp4);

                        getContentPane().add(btn_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 360, 50));

                        nombres.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nombres.setLayout(new java.awt.GridLayout(1, 0));

                        nb1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        nb1.setText("1");
                        nb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        nombres.add(nb1);

                        nb2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        nb2.setText("2");
                        nb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        nombres.add(nb2);

                        nb3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        nb3.setText("3");
                        nb3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        nombres.add(nb3);

                        nb4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nb4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        nb4.setText("4");
                        nb4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        nombres.add(nb4);

                        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 360, 140));

                        jPanel3.setLayout(new java.awt.GridLayout(1, 4));

                        btm1.setText("\\/");
                        btm1.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btm1MouseClicked(evt);
                            }
                        });
                        jPanel3.add(btm1);

                        btm2.setText("\\/");
                        btm2.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btm2MouseClicked(evt);
                            }
                        });
                        jPanel3.add(btm2);

                        btm3.setText("\\/");
                        btm3.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btm3MouseClicked(evt);
                            }
                        });
                        jPanel3.add(btm3);

                        btm4.setText("\\/");
                        btm4.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btm4MouseClicked(evt);
                            }
                        });
                        jPanel3.add(btm4);

                        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 360, 50));
                        getContentPane().add(label_juste, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));
                        getContentPane().add(label_trh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));
                        getContentPane().add(label_trb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

                        btn_check.setText("vérifier");
                        btn_check.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btn_checkMouseClicked(evt);
                            }
                        });
                        getContentPane().add(btn_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

                        jLabel2.setText("Tentatives");
                        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

                        label_nb_tentatives.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                        label_nb_tentatives.setText("0 sur 5");
                        getContentPane().add(label_nb_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 90, 50));

                        btn_recom.setText("Recommencer");
                        btn_recom.addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btn_recomMouseClicked(evt);
                            }
                        });
                        getContentPane().add(btn_recom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

                        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
                        jLabel3.setText("Bravo !!!");
                        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 210, 70));

                        jLabel4.setText("nombre de points :");
                        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 110, 20));
                        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 40, 20));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void btp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btp1ActionPerformed

    private void btp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btp1MouseClicked
joueur[0] = cerveau_jeu.incrementer(joueur[0]);
    nb1.setText(String.valueOf(joueur[0]));
    }//GEN-LAST:event_btp1MouseClicked

    private void btm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm1MouseClicked
    joueur[0] = cerveau_jeu.decrementer(joueur[0]);
    nb1.setText(String.valueOf(joueur[0]));
    }//GEN-LAST:event_btm1MouseClicked

    private void btp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btp2MouseClicked
joueur[1] = cerveau_jeu.incrementer(joueur[1]);
    nb2.setText(String.valueOf(joueur[1]));
    }//GEN-LAST:event_btp2MouseClicked

    private void btm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm2MouseClicked
    joueur[1] = cerveau_jeu.decrementer(joueur[1]);
    nb2.setText(String.valueOf(joueur[1]));
    }//GEN-LAST:event_btm2MouseClicked

    private void btp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btp3MouseClicked
joueur[2] = cerveau_jeu.incrementer(joueur[2]);
    nb3.setText(String.valueOf(joueur[2]));
    }//GEN-LAST:event_btp3MouseClicked

    private void btm3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm3MouseClicked
    joueur[2] = cerveau_jeu.decrementer(joueur[2]);
    nb3.setText(String.valueOf(joueur[2]));
    }//GEN-LAST:event_btm3MouseClicked

    private void btp4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btp4MouseClicked
joueur[3] = cerveau_jeu.incrementer(joueur[3]);
    nb4.setText(String.valueOf(joueur[3]));
    }//GEN-LAST:event_btp4MouseClicked

    private void btm4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btm4MouseClicked
    joueur[3] = cerveau_jeu.decrementer(joueur[3]);
    nb4.setText(String.valueOf(joueur[3]));
    }//GEN-LAST:event_btm4MouseClicked

    private int[] joueur = new int[4];
    
    private void btn_checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_checkMouseClicked
                                          if (essaisRestants <= 0) {
        JOptionPane.showMessageDialog(this, "Vous n'avez plus d'essais !");
        return;
    }

    essaisRestants--;
    label_nb_tentatives.setText((10 - essaisRestants) + " sur 10"); // <-- ligne à ajouter

    int[] resultat = cerveau_jeu.comparerPlusMoins(joueur, cerveau.suiteMachine);

    if (resultat[0] == 4) {
        compteur++;
        jLabel3.setText("Bravo!!!");
        jLabel5.setText(String.valueOf(compteur));
    }

    label_juste.setText("Bonnes réponses : " + resultat[0]);
    label_trh.setText("Trop élevés : " + resultat[2]);
    label_trb.setText("Trop bas : " + resultat[1]);

    }//GEN-LAST:event_btn_checkMouseClicked

    private void btn_recomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recomMouseClicked
jLabel3.setText("");
    cerveau.nouvellePartie();
        for (int i = 0; i < 4; i++) {
        joueur[i] = 0;          // Valeurs de départ pour le joueur
    }
       majLabels();
    }//GEN-LAST:event_btn_recomMouseClicked

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interf_graphique().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm1;
    private javax.swing.JButton btm2;
    private javax.swing.JButton btm3;
    private javax.swing.JButton btm4;
    private javax.swing.JButton btn_check;
    private javax.swing.JPanel btn_plus;
    private javax.swing.JButton btn_recom;
    private javax.swing.JButton btp1;
    private javax.swing.JButton btp2;
    private javax.swing.JButton btp3;
    private javax.swing.JButton btp4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_juste;
    private javax.swing.JLabel label_nb_tentatives;
    private javax.swing.JLabel label_trb;
    private javax.swing.JLabel label_trh;
    private javax.swing.JLabel nb1;
    private javax.swing.JLabel nb2;
    private javax.swing.JLabel nb3;
    private javax.swing.JLabel nb4;
    private javax.swing.JPanel nombres;
    // End of variables declaration//GEN-END:variables

    
    private void majLabels() {
    nb1.setText(String.valueOf(joueur[0]));
    nb2.setText(String.valueOf(joueur[1]));
    nb3.setText(String.valueOf(joueur[2]));
    nb4.setText(String.valueOf(joueur[3]));
}
}