/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chalu
 */
public class Interf_graphique extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interf_graphique.class.getName());

    /**
     * Creates new form Interf_graphique
     */
    public Interf_graphique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_plus = new javax.swing.JPanel();
        btp1 = new javax.swing.JButton();
        btp2 = new javax.swing.JButton();
        btp3 = new javax.swing.JButton();
        btp4 = new javax.swing.JButton();
        nombres = new javax.swing.JPanel();
        nb1 = new javax.swing.JLabel();
        nb2 = new javax.swing.JLabel();
        nb3 = new javax.swing.JLabel();
        nb4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btm1 = new javax.swing.JButton();
        btm2 = new javax.swing.JButton();
        btm3 = new javax.swing.JButton();
        btm4 = new javax.swing.JButton();
        label_juste = new javax.swing.JLabel();
        label_trh = new javax.swing.JLabel();
        label_trb = new javax.swing.JLabel();
        btn_check = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        label_nb_tentatives = new javax.swing.JLabel();
        btn_recom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Trouve le bon code en 5 tentatives !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 310, 40));

        btn_plus.setLayout(new java.awt.GridLayout(1, 4));

        btp1.setText("/\\");
            btp1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btp1ActionPerformed(evt);
                }
            });
            btn_plus.add(btp1);

            btp2.setText("/\\");
                btn_plus.add(btp2);

                btp3.setText("/\\");
                    btn_plus.add(btp3);

                    btp4.setText("/\\");
                        btn_plus.add(btp4);

                        getContentPane().add(btn_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 360, 50));

                        nombres.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nombres.setLayout(new java.awt.GridLayout());

                        nb1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nb1.setText("1");
                        nb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        nombres.add(nb1);

                        nb2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nb2.setText("2");
                        nb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        nombres.add(nb2);

                        nb3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nb3.setText("3");
                        nb3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        nombres.add(nb3);

                        nb4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        nb4.setText("4");
                        nb4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        nombres.add(nb4);

                        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 360, 140));

                        jPanel3.setLayout(new java.awt.GridLayout(1, 4));

                        btm1.setText("\\/");
                        jPanel3.add(btm1);

                        btm2.setText("\\/");
                        jPanel3.add(btm2);

                        btm3.setText("\\/");
                        jPanel3.add(btm3);

                        btm4.setText("\\/");
                        jPanel3.add(btm4);

                        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 360, 50));

                        label_juste.setText("jLabel2");
                        getContentPane().add(label_juste, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

                        label_trh.setText("jLabel2");
                        getContentPane().add(label_trh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

                        label_trb.setText("jLabel2");
                        getContentPane().add(label_trb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

                        btn_check.setText("vérifier");
                        getContentPane().add(btn_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

                        jLabel2.setText("Tentatives");
                        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

                        label_nb_tentatives.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                        label_nb_tentatives.setText("0 sur 5");
                        getContentPane().add(label_nb_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 90, 50));

                        btn_recom.setText("Recommencer");
                        getContentPane().add(btn_recom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void btp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interf_graphique().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm1;
    private javax.swing.JButton btm2;
    private javax.swing.JButton btm3;
    private javax.swing.JButton btm4;
    private javax.swing.JButton btn_check;
    private javax.swing.JPanel btn_plus;
    private javax.swing.JButton btn_recom;
    private javax.swing.JButton btp1;
    private javax.swing.JButton btp2;
    private javax.swing.JButton btp3;
    private javax.swing.JButton btp4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_juste;
    private javax.swing.JLabel label_nb_tentatives;
    private javax.swing.JLabel label_trb;
    private javax.swing.JLabel label_trh;
    private javax.swing.JLabel nb1;
    private javax.swing.JLabel nb2;
    private javax.swing.JLabel nb3;
    private javax.swing.JLabel nb4;
    private javax.swing.JPanel nombres;
    // End of variables declaration//GEN-END:variables
}
